version: 2.1

orbs:
  node: circleci/node@5.0.0
  aws-s3: circleci/aws-s3@2.0.3
  aws-cloudfront: circleci/aws-cloudfront@1.3.0

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: 'npm install'
      - run:
          name: Build React App
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - aws-s3/sync:
          from: /workspace/build/
          to: 's3://your-s3-bucket-name/'
          acl: public-read
      - aws-cloudfront/invalidate:
          distribution-id: 'YOUR_CLOUDFRONT_DISTRIBUTION_ID'
          paths: '/*'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold